from ...Kernel.modules import imgui

class GUIFlags:
    __slots__ = ()

    NONE = imgui.NONE

    # WINDOW
    
    WINDOW_NO_TITLE_BAR = imgui.WINDOW_NO_TITLE_BAR
    WINDOW_NO_RESIZE = imgui.WINDOW_NO_RESIZE
    WINDOW_NO_MOVE = imgui.WINDOW_NO_MOVE
    WINDOW_NO_SCROLLBAR = imgui.WINDOW_NO_SCROLLBAR
    WINDOW_NO_SCROLL_WITH_MOUSE = imgui.WINDOW_NO_SCROLL_WITH_MOUSE
    WINDOW_NO_COLLAPSE = imgui.WINDOW_NO_COLLAPSE
    WINDOW_ALWAYS_AUTO_RESIZE = imgui.WINDOW_ALWAYS_AUTO_RESIZE
    WINDOW_NO_SAVED_SETTINGS = imgui.WINDOW_NO_SAVED_SETTINGS
    WINDOW_NO_INPUTS = imgui.WINDOW_NO_INPUTS
    WINDOW_MENU_BAR = imgui.WINDOW_MENU_BAR
    WINDOW_HORIZONTAL_SCROLLING_BAR = imgui.WINDOW_HORIZONTAL_SCROLLING_BAR
    WINDOW_NO_FOCUS_ON_APPEARING = imgui.WINDOW_NO_FOCUS_ON_APPEARING
    WINDOW_NO_BRING_TO_FRONT_ON_FOCUS = imgui.WINDOW_NO_BRING_TO_FRONT_ON_FOCUS
    WINDOW_ALWAYS_VERTICAL_SCROLLBAR = imgui.WINDOW_ALWAYS_VERTICAL_SCROLLBAR
    WINDOW_ALWAYS_HORIZONTAL_SCROLLBAR = imgui.WINDOW_ALWAYS_HORIZONTAL_SCROLLBAR
    WINDOW_ALWAYS_USE_WINDOW_PADDING = imgui.WINDOW_ALWAYS_USE_WINDOW_PADDING

    # SELECTABLE

    SELECTABLE_DONT_CLOSE_POPUPS = imgui.SELECTABLE_DONT_CLOSE_POPUPS
    SELECTABLE_SPAN_ALL_COLUMNS = imgui.SELECTABLE_SPAN_ALL_COLUMNS
    SELECTABLE_ALLOW_DOUBLE_CLICK = imgui.SELECTABLE_ALLOW_DOUBLE_CLICK

    # INPUT TEXT

    INPUT_TEXT_CHARS_DECIMAL = imgui.INPUT_TEXT_CHARS_DECIMAL
    INPUT_TEXT_CHARS_HEXADECIMAL = imgui.INPUT_TEXT_CHARS_HEXADECIMAL
    INPUT_TEXT_CHARS_UPPERCASE = imgui.INPUT_TEXT_CHARS_UPPERCASE
    INPUT_TEXT_CHARS_NO_BLANK = imgui.INPUT_TEXT_CHARS_NO_BLANK
    INPUT_TEXT_AUTO_SELECT_ALL = imgui.INPUT_TEXT_AUTO_SELECT_ALL
    INPUT_TEXT_ENTER_RETURNS_TRUE = imgui.INPUT_TEXT_ENTER_RETURNS_TRUE
    INPUT_TEXT_CALLBACK_COMPLETION = imgui.INPUT_TEXT_CALLBACK_COMPLETION
    INPUT_TEXT_CALLBACK_HISTORY = imgui.INPUT_TEXT_CALLBACK_HISTORY
    INPUT_TEXT_CALLBACK_ALWAYS = imgui.INPUT_TEXT_CALLBACK_ALWAYS
    INPUT_TEXT_CALLBACK_CHAR_FILTER = imgui.INPUT_TEXT_CALLBACK_CHAR_FILTER
    INPUT_TEXT_ALLOW_TAB_INPUT = imgui.INPUT_TEXT_ALLOW_TAB_INPUT
    INPUT_TEXT_CTRL_ENTER_FOR_NEW_LINE = imgui.INPUT_TEXT_CTRL_ENTER_FOR_NEW_LINE
    INPUT_TEXT_NO_HORIZONTAL_SCROLL = imgui.INPUT_TEXT_NO_HORIZONTAL_SCROLL
    INPUT_TEXT_ALWAYS_INSERT_MODE = imgui.INPUT_TEXT_ALWAYS_INSERT_MODE
    INPUT_TEXT_READ_ONLY = imgui.INPUT_TEXT_READ_ONLY
    INPUT_TEXT_PASSWORD = imgui.INPUT_TEXT_PASSWORD

    # SLIDER FLAGS

    SLIDER_FLAGS_NONE = imgui.SLIDER_FLAGS_NONE
    SLIDER_FLAGS_ALWAYS_CLAMP = imgui.SLIDER_FLAGS_ALWAYS_CLAMP
    SLIDER_FLAGS_LOGARITHMIC = imgui.SLIDER_FLAGS_LOGARITHMIC
    SLIDER_FLAGS_NO_ROUND_TO_FORMAT = imgui.SLIDER_FLAGS_NO_ROUND_TO_FORMAT
    SLIDER_FLAGS_NO_INPUT = imgui.SLIDER_FLAGS_NO_INPUT

    # COMBO

    COMBO_NONE = imgui.COMBO_NONE
    COMBO_POPUP_ALIGN_LEFT  = imgui.COMBO_POPUP_ALIGN_LEFT
    COMBO_HEIGHT_SMALL = imgui.COMBO_HEIGHT_SMALL
    COMBO_HEIGHT_REGULAR = imgui.COMBO_HEIGHT_REGULAR
    COMBO_HEIGHT_LARGE = imgui.COMBO_HEIGHT_LARGE
    COMBO_HEIGHT_LARGEST = imgui.COMBO_HEIGHT_LARGEST
    COMBO_NO_ARROW_BUTTON = imgui.COMBO_NO_ARROW_BUTTON
    COMBO_NO_PREVIEW = imgui.COMBO_NO_PREVIEW
    COMBO_HEIGHT_MASK = imgui.COMBO_HEIGHT_MASK

    # TAB BAR

    TAB_BAR_NONE = imgui.TAB_BAR_NONE
    TAB_BAR_REORDERABLE = imgui.TAB_BAR_REORDERABLE
    TAB_BAR_AUTO_SELECT_NEW_TABS = imgui.TAB_BAR_AUTO_SELECT_NEW_TABS
    TAB_BAR_TAB_LIST_POPUP_BUTTON = imgui.TAB_BAR_TAB_LIST_POPUP_BUTTON
    TAB_BAR_NO_CLOSE_WITH_MIDDLE_MOUSE_BUTTON = imgui.TAB_BAR_NO_CLOSE_WITH_MIDDLE_MOUSE_BUTTON
    TAB_BAR_NO_TAB_LIST_SCROLLING_BUTTONS = imgui.TAB_BAR_NO_TAB_LIST_SCROLLING_BUTTONS
    TAB_BAR_NO_TOOLTIP = imgui.TAB_BAR_NO_TOOLTIP
    TAB_BAR_FITTING_POLICY_RESIZE_DOWN = imgui.TAB_BAR_FITTING_POLICY_RESIZE_DOWN
    TAB_BAR_FITTING_POLICY_SCROLL = imgui.TAB_BAR_FITTING_POLICY_SCROLL
    TAB_BAR_FITTING_POLICY_MASK = imgui.TAB_BAR_FITTING_POLICY_MASK
    TAB_BAR_FITTING_POLICY_DEFAULT = imgui.TAB_BAR_FITTING_POLICY_DEFAULT

    TAB_ITEM_NONE = imgui.TAB_ITEM_NONE
    TAB_ITEM_UNSAVED_DOCUMENT = imgui.TAB_ITEM_UNSAVED_DOCUMENT
    TAB_ITEM_SET_SELECTED = imgui.TAB_ITEM_SET_SELECTED
    TAB_ITEM_NO_CLOSE_WITH_MIDDLE_MOUSE_BUTTON = imgui.TAB_ITEM_NO_CLOSE_WITH_MIDDLE_MOUSE_BUTTON
    TAB_ITEM_NO_PUSH_ID = imgui.TAB_ITEM_NO_PUSH_ID
    TAB_ITEM_NO_TOOLTIP = imgui.TAB_ITEM_NO_TOOLTIP
    TAB_ITEM_NO_REORDER = imgui.TAB_ITEM_NO_REORDER
    TAB_ITEM_LEADING = imgui.TAB_ITEM_LEADING
    TAB_ITEM_TRAILING = imgui.TAB_ITEM_TRAILING
