from OpenGL.GLUT import GLUT_BITMAP_HELVETICA_10, GLUT_BITMAP_HELVETICA_12, GLUT_BITMAP_HELVETICA_18, GLUT_BITMAP_TIMES_ROMAN_10, GLUT_BITMAP_TIMES_ROMAN_24 # type: ignore
from .kernel import log_system

log_system.addInfo("Loading OpenGL fonts")

fonts = {
    "HELVETICA 10":GLUT_BITMAP_HELVETICA_10,
    "HELVETICA 12":GLUT_BITMAP_HELVETICA_12,
    "HELVETICA 18":GLUT_BITMAP_HELVETICA_18,
    "ROMAN 10":GLUT_BITMAP_TIMES_ROMAN_10,
    "ROMAN 24":GLUT_BITMAP_TIMES_ROMAN_24
}